### PR TITLE
Remove region export in prtvol2csv

### PR DESCRIPTION
**Pull request by berland**
Based on top of typehinting branch, look only at the second commit when reviewing.

### CODE REVIEW

**Comment by berland** [comment]
The region export is removed to facilitate refactoring in `fipmapper` which is due to be moved into `fmu.tools`. `fipmapper` will be extended to automatically determine which fipnum-region-zones are comparable in volumes based on a fipmap.

**Review by eivindsm — COMMENTED** [review]
This PR looks good to me, but as I am not familiar with type hinting in the first place I propose to ask for a review from an IT professional, eg someone from SIB.

Question: are you proposing type hinting to be added to the style recommendation for the repo? This will increase the threshold for contributors, and should probably be aligned a bit before introduced. I'm not opposing type hinting, but worry that the threshold for contributing code becomes to demanding at some point.

**Comment by berland** [comment]
> Question: are you proposing type hinting to be added to the style recommendation for the repo? This will increase the threshold for contributors, and should probably be aligned a bit before introduced. I'm not opposing type hinting, but worry that the threshold for contributing code becomes to demanding at some point.

Not added as a recommendation yet, and definitely not as a a requirement.

**Comment by berland** [comment]
> This PR looks good to me, but as I am not familiar with type hinting in the first place I propose to ask for a review from an IT professional, eg someone from SIB.

The type hinting is reviewed in #362 . Your review of this PR only needs to encompass the second commit ;)

**Review by eivindsm — APPROVED** [review]
Second commit looks good

**Comment by berland** [comment]
Converted to draft to ensure #362 is reviewed and merged first.

**Pull request merged**
