### PR TITLE
Use sunsch updated time_vector.py

### PR DESCRIPTION
**Pull request by alifbe**
Use @vkip updated time_vector.py to be compatible with opm 2024.4

https://github.com/OPM/opm-common/pull/4165

### CODE REVIEW

**Review by mferrera — APPROVED** [review]

**Comment by asnyv** [comment]
We just removed the copied code from last time there was a fix in opm (https://github.com/equinor/subscript/pull/720). I really think we should try to avoid having this code in subscript. Either push for a patch release in opm-common or wait for the next (as far as I know we have lived without the functionality in https://github.com/OPM/opm-common/pull/4165 for a long time.

**Comment by alifbe** [comment]
> We just removed the copied code from last time there was a fix in opm (#720). I really think we should try to avoid having this code in subscript. Either push for a patch release in opm-common or wait for the next (as far as I know we have lived without the functionality in [OPM/opm-common#4165](https://github.com/OPM/opm-common/pull/4165) for a long time.

@asnyv Yes, I totally agreed with you. But we got a report where user has crash when they have `BRANPROP` keyword in schedule section due to the changes in OPM 2024.4 
https://equinor.slack.com/archives/CKC3ST0UT/p1723631464314409

We will revert this once PR in OPM is released (probably in 2024.10)

**Comment by asnyv** [comment]
@alifbe alternatively pin opm to 2023.10 until the fix is in place in 2024.10?

**Comment by mferrera** [comment]
Seeking to pin opm for the August Komodo was part of the plan as well. In our discussion about this, and trying to account for all the moving parts with RHEL8 etc, we thought reverting this change would be needed too. But I think now, maybe it is not?

**Comment by asnyv** [comment]
I'm not going to completely block this PR of course but I would at least recommend to check if a pin is sufficient first.

**Comment by mferrera** [comment]
For posterity, we decided to merge this as it contains an additional patch fix going into OPM's time_vector.py as well, and pinning OPM < 2024.4 interferes will cause us to lack RHEL8 compatibility. We will revert the change when 2024.10 comes out

**Pull request merged**
