### PR TITLE
Change column name WATER_PORV to WATPV_TOTAL in prtvol2csv

### PR DESCRIPTION
**Pull request by berland**

### CODE REVIEW

**Comment by berland** [comment]
@asnyv , is Webviz using this CSV output directly and does it need a change as well?

**Comment by asnyv** [comment]
> @asnyv , is Webviz using this CSV output directly and does it need a change as well?

Nope, at least not as far as I know. Some of the other column names are used to add some descriptive text (but they are mainly based on the RMS Volumetrics job output). Will at least be very suprised if this change is breaking anything in webviz-subsurface.

Any other motivation behind this change than to keep the same format as for oil and gas? 
Asking because I'm not sure myself: Are all of these names consistent with the corresponding column names (if they exist) that the RMS 3D Volumetrics job exports? Nice to keep the same convention to make it easy to compare RMS output with initialized Eclipse volumes (though the RMS calculations are often quite simplified).

**Review by rnyb — APPROVED** [review]

**Comment by rnyb** [comment]
We should also consider renaming WATER_TOTAL to WIIP_TOTAL  (WIIP = Water Initially In Placce) 

(equivalent to  the  oil STOIIP_TOTAL and gas  GIIP_TOTAL columns)

**Comment by berland** [comment]
https://github.com/equinor/ecl2df/pull/271 changes WATER_TOTAL to WIIP_TOTAL.

**Pull request merged**
