### PR TITLE
Add new commandline option to casegen_upcars

### PR DESCRIPTION
**Pull request by alifbe**
Request from user to add option to remove all streaks from command line. In addition, replace np.float to float in order to silence the warning.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by berland** [comment]
Looks good. Could you also have a quick look at #361 ? Thanks

**Review by berland — APPROVED** [review]

**Comment by alifbe** [comment]
> Looks good. Could you also have a quick look at #361 ? Thanks

Thanks @berland

I'll add more test case to improve coverage. Should I open a new pull request or just add on this?

**Comment by berland** [comment]
> Should I open a new pull request or just add on this?

Your choice. PS: You will have to rebase on #364  or wait for it to be merged before tests pass again.

**Pull request merged**
